# HW 2.7

In [1]:
import numpy as np
import pandas as pd

In [2]:
y = np.array([110, 140, 180, 190])
X = np.array([1, 180, 150, 1, 150, 175, 1, 170, 165, 1, 185, 210]).reshape(4,-1)
X

array([[  1, 180, 150],
       [  1, 150, 175],
       [  1, 170, 165],
       [  1, 185, 210]])

## (a)

In [3]:
def mle_ite(Nsim, tol):
    i = 0
    theta = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
    while i < Nsim:
        sigma = (y - X.dot(theta)).reshape(-1,1).dot((y - X.dot(theta)).reshape(1,-1))
        theta1 = np.linalg.inv(X.T.dot(np.linalg.inv(sigma)).dot(X)).dot(X.T).dot(np.linalg.inv(sigma)).dot(y)
        i += 1
        
        if np.square((theta1 - theta)).sum() <= tol:
            print('Total %d' %i  ,'iteration')
            return theta1,sigma
        theta = theta1
    
    print('Total %d' %i  ,'iteration')
    return theta,sigma

In [4]:
theta, sigma = mle_ite(1000,0.01)

Total 1 iteration


In [5]:
theta, sigma

(array([-50.45722366,   0.11595569,   1.06057035]),
 array([[ 380.26378754,  244.45529199, -697.15027716,   72.43119763],
        [ 244.45529199,  157.14983056, -448.16803531,   46.56291276],
        [-697.15027716, -448.16803531, 1278.10884145, -132.79052898],
        [  72.43119763,   46.56291276, -132.79052898,   13.7964186 ]]))

## (b)

In [113]:
x = np.array([1, 175,170])

In [114]:
x.dot(theta)

150.13198208812736

## (c)

In [115]:
A = np.linalg.inv(X.T.dot(np.linalg.inv(sigma)).dot(X))
A

array([[ 9.92008795e-15, -1.75058852e-16,  1.25555732e-16],
       [-2.29611375e-16,  2.31576551e-17, -1.94100457e-17],
       [ 1.73129595e-16, -1.95450278e-17,  1.64225156e-17]])

In [120]:
ME = np.sqrt(x.dot(A).dot(x))*1.96
ME

2.3828115169069767e-07

In [119]:
x.dot(theta) - ME

150.1319818498462

## (d)

In [122]:
D = X.T.dot(np.linalg.inv(sigma)).dot(X)
D

array([[-3.80643042e+14, -1.70978760e+17, -1.99172509e+17],
       [-1.66683774e+17, -5.73462784e+19, -6.65041706e+19],
       [-1.94363549e+17, -6.64473793e+19, -7.69884006e+19]])